version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:v0.14
    depends_on:
      - breedbase_db
    container_name: breedbase_web
    ports:
      - 7080:8080
    volumes:
      - type: bind
        source: ./repos/cxgn-corelibs
        target: /home/production/cxgn/cxgn-corlibs
      - type: bind
        source: ./repos/local-lib
        target: /home/production/cxgn/local-lib
      - type: bind
        source: ./repos/Phenome
        target: /home/production/cxgn/Phenome
      - type: bind
        source: ./repos/sgn
        target: /home/production/cxgn/sgn
      - type: bind
        source: ./sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: ./repos/R_libs
        target: /home/production/cxgn/R_libs
      - type: bind
        source: ./repos/famosolab-breedbase
        target: /home/production/cxgn/famosolab-breedbase
      - type: bind
        source: ./repos/famosolab-breedbase/lsu_img
        target: /home/production/cxgn/sgn/documents/lsu_img
      - type: bind
        source: ./archive
        target: /home/production/archive
      - type: bind
        source: ./tmp
        target: /home/production/tmp
      - type: bind
        source: ./cache
        target: /home/production/cache
      - type: bind
        source: ./cluster
        target: /home/production/cluster
      - type: bind
        source: ./images
        target: /home/production/public/images    
  breedbase_db:
    image: breedbase/pg:latest
    container_name: breedbase_db
    ports:
      - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:
    name: bb_postgres
